version: "3.8"
services:
  postgres:
    image: postgres
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: revenue_system
      POSTGRES_USER: root
      POSTGRES_PASSWORD: revenue1234
      TZ: Asia/Seoul
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - revenue-system

  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - revenue-system
    volumes:
      - redis_data:/data

#  spring:
#    build:
#      dockerfile: ./Dockerfile
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://my-postgres:5432/revenue_system
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=revenue1234
#      - SPRING_REDIS_HOST=my-redis
#      - SPRING_REDIS_PORT=6379
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres
#      - redis
#    networks:
#      - revenue-system

volumes:
  postgres_data:
  redis_data:

networks:
  revenue-system:
    name: revenue-system