spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://my-postgres:5432/revenue_system
    username: root
    password: revenue1234
    driver-class-name: org.postgresql.Driver