spring:
  application:
    name: revenue-management

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: local
    include: oauth, jwt

  batch:
    job:
      enabled: false

    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-postgresql.sql

    chunk:
      size: 200

    pool:
      size: 5