spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: batch
          uri: lb://batch
          predicates:
            - Path=/batch/api/statistics/**
          filters:
            - StripPrefix=1
#            - name: JwtFilter
        - id: batch
          uri: lb://batch
          predicates:
            - Path=/batch/api/adjustment/**
          filters:
            - StripPrefix=1
#            - name: JwtFilter


server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://127.0.0.1:8761/eureka/}
